on:
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
    - name: Download and Verify Package Dependencies
      run: mvn --batch-mode --update-snapshots verify
    - name: Run Unit Tests
      run: mvn test
    - name: Package Yamcs
      run: mvn clean package